version: '3.8'

services:
  api:
    container_name: appgestorapi
    image: appgestorapi:latest
    build:
      context: ./servidor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DOCKER_CONTAINER=1
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - appgestornetwork

  cliente:
    container_name: appgestorcliente
    image: appgestorcliente:latest
    build:
      context: ./cliente
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DOCKER_CONTAINER=1
    depends_on:
      - api
    networks:
      - appgestornetwork

  web:
    container_name: appgestorweb
    image: appgestorweb:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DOCKER_CONTAINER=1
    networks:
      - appgestornetwork

  database:
    container_name: appgestordatabase
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${CONTRASENASQL}
      - MARIADB_DATABASE=${DATABASESQL}
    ports:
      - "3306:3306"
    volumes:
      - ./datos_mariadb/data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - appgestornetwork

networks:
  appgestornetwork:
    driver: bridge
