const getSalidasService: string = "SELECT sp.id, sp.producto_final_id, sp.formula_id, sp.numero_lote, sp.fecha_salida, sp.cantidad, sp.fecha_caducidad, sp.envasado_id AS envasado_id, e.nombre AS envasado_nombre, sp.formato_id AS formato_id, f.nombre AS formato_nombre, sp.destino_id AS destino_id, d.nombre AS destino_nombre, sp.vehiculo_id AS vehiculo_id, v.matricula AS vehiculo_matricula, sp.id_proyecto AS proyecto_id, p.nombre AS proyecto_nombre, p.nif AS proyecto_nif, p.direccion AS proyecto_direccion, p.codigo_postal AS proyecto_codigo_postal, p.poblacion AS proyecto_poblacion, p.telefono AS proyecto_telefono, p.correo_electronico AS proyecto_correo_electronico, p.logo AS proyecto_logo FROM salida_de_productos sp JOIN proyectos p ON sp.id_proyecto = p.id JOIN envasados e ON sp.envasado_id = e.id JOIN formatos f ON sp.formato_id = f.id JOIN destinos d ON sp.destino_id = d.id JOIN vehiculos v ON sp.vehiculo_id = v.id";

const getSalidasByProductoFinalService: string = "SELECT sp.id, sp.producto_final_id, sp.formula_id, sp.numero_lote, sp.fecha_salida, sp.cantidad, sp.fecha_caducidad, sp.envasado_id AS envasado_id, e.nombre AS envasado_nombre, sp.formato_id AS formato_id, f.nombre AS formato_nombre, sp.destino_id AS destino_id, d.nombre AS destino_nombre, sp.vehiculo_id AS vehiculo_id, v.matricula AS vehiculo_matricula, sp.id_proyecto AS proyecto_id, p.nombre AS proyecto_nombre, p.nif AS proyecto_nif, p.direccion AS proyecto_direccion, p.codigo_postal AS proyecto_codigo_postal, p.poblacion AS proyecto_poblacion, p.telefono AS proyecto_telefono, p.correo_electronico AS proyecto_correo_electronico, p.logo AS proyecto_logo FROM salida_de_productos sp JOIN proyectos p ON sp.id_proyecto = p.id JOIN envasados e ON sp.envasado_id = e.id JOIN formatos f ON sp.formato_id = f.id JOIN destinos d ON sp.destino_id = d.id JOIN vehiculos v ON sp.vehiculo_id = v.id WHERE sp.producto_final_id = ?";

const getSalidasByFechaSalidaService: string = "SELECT sp.id, sp.producto_final_id, sp.formula_id, sp.numero_lote, sp.fecha_salida, sp.cantidad, sp.fecha_caducidad, sp.envasado_id AS envasado_id, e.nombre AS envasado_nombre, sp.formato_id AS formato_id, f.nombre AS formato_nombre, sp.destino_id AS destino_id, d.nombre AS destino_nombre, sp.vehiculo_id AS vehiculo_id, v.matricula AS vehiculo_matricula, sp.id_proyecto AS proyecto_id, p.nombre AS proyecto_nombre, p.nif AS proyecto_nif, p.direccion AS proyecto_direccion, p.codigo_postal AS proyecto_codigo_postal, p.poblacion AS proyecto_poblacion, p.telefono AS proyecto_telefono, p.correo_electronico AS proyecto_correo_electronico, p.logo AS proyecto_logo FROM salida_de_productos sp JOIN proyectos p ON sp.id_proyecto = p.id JOIN envasados e ON sp.envasado_id = e.id JOIN formatos f ON sp.formato_id = f.id JOIN destinos d ON sp.destino_id = d.id JOIN vehiculos v ON sp.vehiculo_id = v.id WHERE sp.fecha_salida = ?";

const getSalidasByProyectoService: string = "SELECT sp.id, sp.producto_final_id, sp.formula_id, sp.numero_lote, sp.fecha_salida, sp.cantidad, sp.fecha_caducidad, sp.envasado_id AS envasado_id, e.nombre AS envasado_nombre, sp.formato_id AS formato_id, f.nombre AS formato_nombre, sp.destino_id AS destino_id, d.nombre AS destino_nombre, sp.vehiculo_id AS vehiculo_id, v.matricula AS vehiculo_matricula, sp.id_proyecto AS proyecto_id, p.nombre AS proyecto_nombre, p.nif AS proyecto_nif, p.direccion AS proyecto_direccion, p.codigo_postal AS proyecto_codigo_postal, p.poblacion AS proyecto_poblacion, p.telefono AS proyecto_telefono, p.correo_electronico AS proyecto_correo_electronico, p.logo AS proyecto_logo FROM salida_de_productos sp JOIN proyectos p ON sp.id_proyecto = p.id JOIN envasados e ON sp.envasado_id = e.id JOIN formatos f ON sp.formato_id = f.id JOIN destinos d ON sp.destino_id = d.id JOIN vehiculos v ON sp.vehiculo_id = v.id WHERE sp.id_proyecto = ?";

const postSalidasService: string = "INSERT INTO salida_de_productos (producto_final_id, formula_id, numero_lote, fecha_salida, cantidad, fecha_caducidad, envasado_id, formato_id, destino_id, vehiculo_id, id_proyecto) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

const putSalidasService: string = "UPDATE salida_de_productos SET producto_final_id = ?, formula_id = ?, numero_lote = ?, fecha_salida = ?, cantidad = ?, fecha_caducidad = ?, envasado_id = ?, formato_id = ?, destino_id = ?, vehiculo_id = ?, id_proyecto = ? WHERE id = ?";

const deleteSalidasService: string = "DELETE FROM salida_de_productos WHERE id = ?";

export { 
    getSalidasService, 
    getSalidasByProductoFinalService, 
    getSalidasByFechaSalidaService, 
    getSalidasByProyectoService, 
    postSalidasService, 
    putSalidasService, 
    deleteSalidasService 
};
