apiVersion: apps/v1
kind: Deployment
metadata:
    name: appgestorapi-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: appgestorapi
    template:
        metadata:
            labels:
                app: appgestorapi
        spec:
            containers:
                - name: appgestorapi
                  image: 220286409224.dkr.ecr.us-east-1.amazonaws.com/appgestor
                  ports:
                    - containerPort: 3000