apiVersion: v1
kind: Service
metadata:
    name: appgestorapi-service
    labels:
        env: app
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 3000
    selector:
        app: appgestorapi
