apiVersion: v1
kind: Service
metadata:
    name: mariadb-service
spec:
    type: NodePort
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 30931
    selector:
        app: mariadb
