name: Deploy to Docker Compose on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      run: echo "${{ secrets.EC2_SSH_KEY_PEM }}" > /tmp/ssh_key.pem

    - name: Set permissions for SSH key
      run: chmod 600 /tmp/ssh_key.pem

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: /tmp/ssh_key.pem

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY_PEM }}
        script: |
          cd /home/ubuntu/appgestor/
          git pull origin main
          docker-compose down
          docker-compose up -d --build
