name: Deploy to Docker Compose on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      run: echo "${{ secrets.EC2_SSH_KEY_PEM }}" > /tmp/ssh_key.pem

    - name: Set permissions for SSH key
      run: chmod 600 /tmp/ssh_key.pem

    - name: Start SSH agent and add key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add /tmp/ssh_key.pem

    - name: Add EC2 host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY_PEM }}
        port: 22
        command_timeout: 120s
        script: |
          cd /home/ubuntu/appgestor
          git reset --hard HEAD
          git clean -fd
          git pull origin main
          sudo systemctl stop nginx
          sudo systemctl disable nginx
          sudo docker-compose down
          sudo docker ps -q --filter "status=running" | xargs -r sudo docker stop
          sudo fuser -k 80/tcp
          sudo docker-compose up -d --build
